['tltypes'] = {
	['name'] = 'Acura TL Type-S',
	['brand'] = 'aston',
	['model'] = 'tltypes',
	['price'] = 24000,
	['category'] = 'aston',
	['categoryLabel'] = 'aston',
	['hash'] = `tltypes`,
	['shop'] = 'import',
},
['ast'] = {
	['name'] = '2013 Aston Martin Vanquish',
	['brand'] = 'aston',
	['model'] = 'ast',
	['price'] = 24000,
	['category'] = 'aston',
	['categoryLabel'] = 'aston',
	['hash'] = `ast`,
	['shop'] = 'import',
},
['amdbx'] = {
	['name'] = 'Aston Martin DBX Carbon Edition',
	['brand'] = 'aston',
	['model'] = 'amdbx',
	['price'] = 24000,
	['category'] = 'aston',
	['categoryLabel'] = 'aston',
	['hash'] = `amdbx`,
	['shop'] = 'import',
},
['aaq4'] = {
	['name'] = '2017 Audi A4 Quattro ABT',
	['brand'] = 'audi',
	['model'] = 'aaq4',
	['price'] = 24000,
	['category'] = 'audi',
	['categoryLabel'] = 'audi',
	['hash'] = `aaq4`,
	['shop'] = 'import',
},
['q820'] = {
	['name'] = '2020 Audi Q8 50TDI',
	['brand'] = 'audi',
	['model'] = 'q820',
	['price'] = 15000,
	['category'] = 'audi',
	['categoryLabel'] = 'audi',
	['hash'] = `q820`,
	['shop'] = 'import',
},
['r8ppi'] = {
	['name'] = '2013 Audi R8 V10',
	['brand'] = 'audi',
	['model'] = 'r8ppi',
	['price'] = 19000,
	['category'] = 'audi',
	['categoryLabel'] = 'audi',
	['hash'] = `r8ppi`,
	['shop'] = 'import',
},
['r820'] = {
	['name'] = '2020 Audi R8',
	['brand'] = 'audi',
	['model'] = 'r820',
	['price'] = 55000,
	['category'] = 'audi',
	['categoryLabel'] = 'audi',
	['hash'] = `r820`,
	['shop'] = 'import',
},
['rs6'] = {
	['name'] = '2016 Audi RS6 C7',
	['brand'] = 'audi',
	['model'] = 'rs6',
	['price'] = 35000,
	['category'] = 'audi',
	['categoryLabel'] = 'audi',
	['hash'] = `rs6`,
	['shop'] = 'import',
},
['rs72020'] = {
	['name'] = '2020 Audi RS7',
	['brand'] = 'audi',
	['model'] = 'rs72020',
	['price'] = 28000,
	['category'] = 'audi',
	['categoryLabel'] = 'audi',
	['hash'] = `rs72020`,
	['shop'] = 'import',
},
['sq72016'] = {
	['name'] = '2016 Audi SQ7',
	['brand'] = 'audi',
	['model'] = 'sq72016',
	['price'] = 30000,
	['category'] = 'audi',
	['categoryLabel'] = 'audi',
	['hash'] = `sq72016`,
	['shop'] = 'import',
},
['ttrs'] = {
	['name'] = '2010 Audi TT RS',
	['brand'] = 'audi',
	['model'] = 'ttrs',
	['price'] = 125000,
	['category'] = 'audi',
	['categoryLabel'] = 'audi',
	['hash'] = `ttrs`,
	['shop'] = 'import',
},
['bbentayga'] = {
	['name'] = 'Bentley Bentayga',
	['brand'] = 'bentley',
	['model'] = 'bbentayga',
	['price'] = 20000,
	['category'] = 'bentley',
	['categoryLabel'] = 'bentley',
	['hash'] = `bbentayga`,
	['shop'] = 'import',
},
['cgts'] = {
	['name'] = '2020 Bentley Continental GT Convertible',
	['brand'] = 'bentley',
	['model'] = 'cgts',
	['price'] = 30000,
	['category'] = 'bentley',
	['categoryLabel'] = 'bentley',
	['hash'] = `cgts`,
	['shop'] = 'import',
},
['760li04'] = {
	['name'] = '2004 BMW 760Li Individual (E66/PFL)',
	['brand'] = 'bmw',
	['model'] = '760li04',
	['price'] = 40000,
	['category'] = 'bmw',
	['categoryLabel'] = 'bmw',
	['hash'] = `760li04`,
	['shop'] = 'import',
},
['m2'] = {
	['name'] = '2016 BMW M2',
	['brand'] = 'bmw',
	['model'] = 'm2',
	['price'] = 12500,
	['category'] = 'bmw',
	['categoryLabel'] = 'bmw',
	['hash'] = `m2`,
	['shop'] = 'import',
},
['m3e36'] = {
	['name'] = '1997 BMW M3 E36',
	['brand'] = 'bmw',
	['model'] = 'm3e36',
	['price'] = 18000,
	['category'] = 'bmw',
	['categoryLabel'] = 'bmw',
	['hash'] = `m3e36`,
	['shop'] = 'import',
},
['m3e92'] = {
	['name'] = '2008 BMW M3 e92',
	['brand'] = 'bmw',
	['model'] = 'm3e92',
	['price'] = 20000,
	['category'] = 'bmw',
	['categoryLabel'] = 'bmw',
	['hash'] = `m3e92`,
	['shop'] = 'import',
},
['x6m'] = {
	['name'] = 'BMW X6M F16',
	['brand'] = 'bmw',
	['model'] = 'x6m',
	['price'] = 20000,
	['category'] = 'bmw',
	['categoryLabel'] = 'bmw',
	['hash'] = `x6m`,
	['shop'] = 'import',
},
['x5e53'] = {
	['name'] = 'BMW X5 E53 2005 Sport Package',
	['brand'] = 'bmw',
	['model'] = 'x5e53',
	['price'] = 20000,
	['category'] = 'bmw',
	['categoryLabel'] = 'bmw',
	['hash'] = `x5e53`,
	['shop'] = 'import',
},
['i8'] = {
	['name'] = '2015 BMW i8 (I12)',
	['brand'] = 'bmw',
	['model'] = 'i8',
	['price'] = 20000,
	['category'] = 'bmw',
	['categoryLabel'] = 'bmw',
	['hash'] = `i8`,
	['shop'] = 'import',
},
['m3f80'] = {
	['name'] = '2015 BMW M3 (F80)',
	['brand'] = 'bmw',
	['model'] = 'm3f80',
	['price'] = 25000,
	['category'] = 'bmw',
	['categoryLabel'] = 'bmw',
	['hash'] = `m3f80`,
	['shop'] = 'import',
},
['bmci'] = {
	['name'] = '2018 BMW M5 F90',
	['brand'] = 'bmw',
	['model'] = 'bmci',
	['price'] = 20000,
	['category'] = 'bmw',
	['categoryLabel'] = 'bmw',
	['hash'] = `bmci`,
	['shop'] = 'import',
},
['m4f82'] = {
	['name'] = '2015 BMW M4 F82',
	['brand'] = 'bmw',
	['model'] = 'm4f82',
	['price'] = 11500,
	['category'] = 'bmw',
	['categoryLabel'] = 'bmw',
	['hash'] = `m4f82`,
	['shop'] = 'import',
},
['m6f13'] = {
	['name'] = 'BMW M6 F13 Shadow Line',
	['brand'] = 'bmw',
	['model'] = 'm6f13',
	['price'] = 16000,
	['category'] = 'bmw',
	['categoryLabel'] = 'bmw',
	['hash'] = `m6f13`,
	['shop'] = 'import',
},
['z419'] = {
	['name'] = '2019 BMW Z4 M40i',
	['brand'] = 'bmw',
	['model'] = 'z419',
	['price'] = 14000,
	['category'] = 'bmw',
	['categoryLabel'] = 'bmw',
	['hash'] = `z419`,
	['shop'] = 'import',
},
['bolide'] = {
	['name'] = '2020 Bugatti Bolide',
	['brand'] = 'bugatti',
	['model'] = 'bolide',
	['price'] = 12500,
	['category'] = 'bugatti',
	['categoryLabel'] = 'bugatti',
	['hash'] = `bolide`,
	['shop'] = 'import',
},
['cats'] = {
	['name'] = '2016 Cadillac ATS-V Coupe',
	['brand'] = 'cadillac',
	['model'] = 'cats',
	['price'] = 7200,
	['category'] = 'cadillac',
	['categoryLabel'] = 'cadillac',
	['hash'] = `cats`,
	['shop'] = 'import',
},
['cesc21'] = {
	['name'] = '2021 Cadillac Escalade',
	['brand'] = 'cadillac',
	['model'] = 'cesc21',
	['price'] = 8000,
	['category'] = 'cadillac',
	['categoryLabel'] = 'cadillac',
	['hash'] = `cesc21`,
	['shop'] = 'import',
},
['09tahoe'] = {
	['name'] = '2009 Chevrolet Tahoe',
	['brand'] = 'chevrolet',
	['model'] = '09tahoe',
	['price'] = 18000,
	['category'] = 'chevrolet',
	['categoryLabel'] = 'chevrolet',
	['hash'] = `09tahoe`,
	['shop'] = 'import',
},
['15tahoe'] = {
	['name'] = '2015 Chevrolet Tahoe',
	['brand'] = 'chevrolet',
	['model'] = '15tahoe',
	['price'] = 10000,
	['category'] = 'chevrolet',
	['categoryLabel'] = 'chevrolet',
	['hash'] = `15tahoe`,
	['shop'] = 'import',
},
['2020ss'] = {
	['name'] = '2020 Chevrolet Camaro SS',
	['brand'] = 'chevrolet',
	['model'] = '2020ss',
	['price'] = 10000,
	['category'] = 'chevrolet',
	['categoryLabel'] = 'chevrolet',
	['hash'] = `2020ss`,
	['shop'] = 'import',
},
['camrs17'] = {
	['name'] = '2017 Chevrolet Camaro RS',
	['brand'] = 'chevrolet',
	['model'] = 'camrs17',
	['price'] = 12000,
	['category'] = 'chevrolet',
	['categoryLabel'] = 'chevrolet',
	['hash'] = `camrs17`,
	['shop'] = 'import',
},
['tahoe21'] = {
	['name'] = '2021 Chevrolet Tahoe RST',
	['brand'] = 'chevrolet',
	['model'] = 'tahoe21',
	['price'] = 45000,
	['category'] = 'chevrolet',
	['categoryLabel'] = 'chevrolet',
	['hash'] = `tahoe21`,
	['shop'] = 'import',
},
['corvettec5z06'] = {
	['name'] = 'Chevrolet Corvette C5 Z06',
	['brand'] = 'chevrolet',
	['model'] = 'corvettec5z06',
	['price'] = 32000,
	['category'] = 'chevrolet',
	['categoryLabel'] = 'chevrolet',
	['hash'] = `corvettec5z06`,
	['shop'] = 'import',
},
['czr1'] = {
	['name'] = '2009 Chevrolet Corvette ZR1',
	['brand'] = 'chevrolet',
	['model'] = 'czr1',
	['price'] = 19000,
	['category'] = 'chevrolet',
	['categoryLabel'] = 'chevrolet',
	['hash'] = `czr1`,
	['shop'] = 'import',
},
['c7'] = {
	['name'] = '2014 Chevrolet Corvette C7 Stingray',
	['brand'] = 'chevrolet',
	['model'] = 'c7',
	['price'] = 29000,
	['category'] = 'chevrolet',
	['categoryLabel'] = 'chevrolet',
	['hash'] = `c7`,
	['shop'] = 'import',
},
['stingray'] = {
	['name'] = '2020 Chevrolet Corvette C8 Stingray',
	['brand'] = 'chevrolet',
	['model'] = 'stingray',
	['price'] = 42000,
	['category'] = 'chevrolet',
	['categoryLabel'] = 'chevrolet',
	['hash'] = `stingray`,
	['shop'] = 'import',
},
['16charger'] = {
	['name'] = '2016 Dodge Charger',
	['brand'] = 'dodge',
	['model'] = '16charger',
	['price'] = 45000,
	['category'] = 'dodge',
	['categoryLabel'] = 'dodge',
	['hash'] = `16charger`,
	['shop'] = 'import',
},
['99viper'] = {
	['name'] = '1999 Dodge Viper GTS ACR',
	['brand'] = 'dodge',
	['model'] = '99viper',
	['price'] = 6500,
	['category'] = 'dodge',
	['categoryLabel'] = 'dodge',
	['hash'] = `99viper`,
	['shop'] = 'import',
},
['chr20'] = {
	['name'] = 'Dodge Charger Hellcat Widebody 2021',
	['brand'] = 'dodge',
	['model'] = 'chr20',
	['price'] = 13000,
	['category'] = 'dodge',
	['categoryLabel'] = 'dodge',
	['hash'] = `chr20`,
	['shop'] = 'import',
},
['demon'] = {
	['name'] = '2018 Dodge Challenger SRT Demon',
	['brand'] = 'dodge',
	['model'] = 'demon',
	['price'] = 18000,
	['category'] = 'dodge',
	['categoryLabel'] = 'dodge',
	['hash'] = `demon`,
	['shop'] = 'import',
},
['raid'] = {
	['name'] = 'Dodge Challenger Raid',
	['brand'] = 'dodge',
	['model'] = 'raid',
	['price'] = 35000,
	['category'] = 'dodge',
	['categoryLabel'] = 'dodge',
	['hash'] = `raid`,
	['shop'] = 'import',
},
['ram2500'] = {
	['name'] = '2015 Dodge RAM 2500',
	['brand'] = 'dodge',
	['model'] = 'ram2500',
	['price'] = 19000,
	['category'] = 'dodge',
	['categoryLabel'] = 'dodge',
	['hash'] = `ram2500`,
	['shop'] = 'import',
},
['srt4'] = {
	['name'] = 'Dodge Neon SRT-4',
	['brand'] = 'dodge',
	['model'] = 'srt4',
	['price'] = 15000,
	['category'] = 'dodge',
	['categoryLabel'] = 'dodge',
	['hash'] = `srt4`,
	['shop'] = 'import',
},
['trx'] = {
	['name'] = '2017 Dodge RAM 1500 Rebel TRX',
	['brand'] = 'dodge',
	['model'] = 'trx',
	['price'] = 19500,
	['category'] = 'dodge',
	['categoryLabel'] = 'dodge',
	['hash'] = `trx`,
	['shop'] = 'import',
},
['16challenger'] = {
	['name'] = '2016 Dodge Challenger',
	['brand'] = 'dodge',
	['model'] = '16challenger',
	['price'] = 12000,
	['category'] = 'dodge',
	['categoryLabel'] = 'dodge',
	['hash'] = `16challenger`,
	['shop'] = 'import',
},
['cutlass'] = {
	['name'] = 'Dacia logan pickup ',
	['brand'] = 'dacia',
	['model'] = 'cutlass',
	['price'] = 12000,
	['category'] = 'dacia',
	['categoryLabel'] = 'dacia',
	['hash'] = `cutlass`,
	['shop'] = 'import',
},
['logan'] = {
	['name'] = '2008 Dacia Logan',
	['brand'] = 'dacia',
	['model'] = 'logan',
	['price'] = 12000,
	['category'] = 'dacia',
	['categoryLabel'] = 'dacia',
	['hash'] = `logan`,
	['shop'] = 'import',
},
['1310'] = {
	['name'] = 'Dacia 1310 2001',
	['brand'] = 'dacia',
	['model'] = '1310',
	['price'] = 12000,
	['category'] = 'dacia',
	['categoryLabel'] = 'dacia',
	['hash'] = `1310`,
	['shop'] = 'import',
},
['sandero'] = {
	['name'] = 'Dacia Sandero 2014',
	['brand'] = 'dacia',
	['model'] = 'sandero',
	['price'] = 12000,
	['category'] = 'dacia',
	['categoryLabel'] = 'dacia',
	['hash'] = `sandero`,
	['shop'] = 'import',
},
['stepway'] = {
	['name'] = 'Dacia Sandero Stepway 2014',
	['brand'] = 'dacia',
	['model'] = 'stepway',
	['price'] = 12000,
	['category'] = 'dacia',
	['categoryLabel'] = 'dacia',
	['hash'] = `stepway`,
	['shop'] = 'import',
},
['488'] = {
	['name'] = 'Ferrari 488 Spider',
	['brand'] = 'ferrari',
	['model'] = '488',
	['price'] = 10800,
	['category'] = 'ferrari',
	['categoryLabel'] = 'ferrari',
	['hash'] = `488`,
	['shop'] = 'import',
},
['f430s'] = {
	['name'] = 'Ferrari F430 Scuderia',
	['brand'] = 'ferrari',
	['model'] = 'f430s',
	['price'] = 14500,
	['category'] = 'ferrari',
	['categoryLabel'] = 'ferrari',
	['hash'] = `f430s`,
	['shop'] = 'import',
},
['f812'] = {
	['name'] = '2018 Ferrari 812 Superfast',
	['brand'] = 'ferrari',
	['model'] = 'f812',
	['price'] = 5500,
	['category'] = 'ferrari',
	['categoryLabel'] = 'ferrari',
	['hash'] = `f812`,
	['shop'] = 'import',
},
['fct'] = {
	['name'] = '2015 Ferrari California T',
	['brand'] = 'ferrari',
	['model'] = 'fct',
	['price'] = 55000,
	['category'] = 'ferrari',
	['categoryLabel'] = 'ferrari',
	['hash'] = `fct`,
	['shop'] = 'import',
},
['fxxk'] = {
	['name'] = 'Ferrari FXX-K Hybrid Hypercar',
	['brand'] = 'ferrari',
	['model'] = 'fxxk',
	['price'] = 8500,
	['category'] = 'ferrari',
	['categoryLabel'] = 'ferrari',
	['hash'] = `fxxk`,
	['shop'] = 'import',
},
['laferrari'] = {
	['name'] = '2015 Ferrari LaFerrari',
	['brand'] = 'ferrari',
	['model'] = 'laferrari',
	['price'] = 12000,
	['category'] = 'ferrari',
	['categoryLabel'] = 'ferrari',
	['hash'] = `laferrari`,
	['shop'] = 'import',
},
['mig'] = {
	['name'] = 'Ferrari Enzo',
	['brand'] = 'ferrari',
	['model'] = 'mig',
	['price'] = 6500,
	['category'] = 'ferrari',
	['categoryLabel'] = 'ferrari',
	['hash'] = `mig`,
	['shop'] = 'import',
},
['yFe458i1'] = {
	['name'] = '458 Italia',
	['brand'] = 'ferrari',
	['model'] = 'yFe458i1',
	['price'] = 7500,
	['category'] = 'ferrari',
	['categoryLabel'] = 'ferrari',
	['hash'] = `yFe458i1`,
	['shop'] = 'import',
},
['yFe458i2'] = {
	['name'] = '458 Speciale',
	['brand'] = 'ferrari',
	['model'] = 'yFe458i2',
	['price'] = 8000,
	['category'] = 'ferrari',
	['categoryLabel'] = 'ferrari',
	['hash'] = `yFe458i2`,
	['shop'] = 'import',
},
['yFe458s1'] = {
	['name'] = '458 Spider',
	['brand'] = 'ferrari',
	['model'] = 'yFe458s1',
	['price'] = 14000,
	['category'] = 'ferrari',
	['categoryLabel'] = 'ferrari',
	['hash'] = `yFe458s1`,
	['shop'] = 'import',
},
['yFe458s2'] = {
	['name'] = '458 Speciale Aperta',
	['brand'] = 'ferrari',
	['model'] = 'yFe458s2',
	['price'] = 5000,
	['category'] = 'ferrari',
	['categoryLabel'] = 'ferrari',
	['hash'] = `yFe458s2`,
	['shop'] = 'import',
},
['yFeF12A'] = {
	['name'] = 'Ferrari F60 America',
	['brand'] = 'ferrari',
	['model'] = 'yFeF12A',
	['price'] = 25000,
	['category'] = 'ferrari',
	['categoryLabel'] = 'ferrari',
	['hash'] = `yFeF12A`,
	['shop'] = 'import',
},
['yFeF12T'] = {
	['name'] = 'Ferrari F12 TRS Roadster',
	['brand'] = 'ferrari',
	['model'] = 'yFeF12T',
	['price'] = 90000,
	['category'] = 'ferrari',
	['categoryLabel'] = 'ferrari',
	['hash'] = `yFeF12T`,
	['shop'] = 'import',
},
['f150'] = {
	['name'] = '2012 Ford F150 SVT Raptor R',
	['brand'] = 'ford',
	['model'] = 'f150',
	['price'] = 130000,
	['category'] = 'ford',
	['categoryLabel'] = 'ford',
	['hash'] = `f150`,
	['shop'] = 'import',
},
['fgt'] = {
	['name'] = '2005 Ford GT',
	['brand'] = 'ford',
	['model'] = 'fgt',
	['price'] = 30000,
	['category'] = 'ford',
	['categoryLabel'] = 'ford',
	['hash'] = `fgt`,
	['shop'] = 'import',
},
['gt17'] = {
	['name'] = '2017 Ford GT',
	['brand'] = 'ford',
	['model'] = 'gt17',
	['price'] = 4000,
	['category'] = 'ford',
	['categoryLabel'] = 'ford',
	['hash'] = `gt17`,
	['shop'] = 'import',
},
['raptor2017'] = {
	['name'] = '2017 Ford Raptor',
	['brand'] = 'ford',
	['model'] = 'raptor2017',
	['price'] = 40000,
	['category'] = 'ford',
	['categoryLabel'] = 'ford',
	['hash'] = `raptor2017`,
	['shop'] = 'import',
},
['wildtrak'] = {
	['name'] = '2021 Ford Bronco Wildtrak',
	['brand'] = 'ford',
	['model'] = 'wildtrak',
	['price'] = 60000,
	['category'] = 'ford',
	['categoryLabel'] = 'ford',
	['hash'] = `wildtrak`,
	['shop'] = 'import',
},
['honcrx91'] = {
	['name'] = 'Honda CRX SiR 1991',
	['brand'] = 'honda',
	['model'] = 'honcrx91',
	['price'] = 55000,
	['category'] = 'honda',
	['categoryLabel'] = 'honda',
	['hash'] = `honcrx91`,
	['shop'] = 'import',
},
['na1'] = {
	['name'] = '1992 Honda NSX-R (NA1)',
	['brand'] = 'honda',
	['model'] = 'na1',
	['price'] = 70000,
	['category'] = 'honda',
	['categoryLabel'] = 'honda',
	['hash'] = `na1`,
	['shop'] = 'import',
},
['ap2'] = {
	['name'] = 'Honda S2000 AP2',
	['brand'] = 'honda',
	['model'] = 'ap2',
	['price'] = 45000,
	['category'] = 'honda',
	['categoryLabel'] = 'honda',
	['hash'] = `ap2`,
	['shop'] = 'import',
},
['fk8'] = {
	['name'] = '2018 Honda Civic Type-R (FK8)',
	['brand'] = 'honda',
	['model'] = 'fk8',
	['price'] = 60000,
	['category'] = 'honda',
	['categoryLabel'] = 'honda',
	['hash'] = `fk8`,
	['shop'] = 'import',
},
['it18'] = {
	['name'] = '2017 Italdesign Zerouno',
	['brand'] = 'italdesign',
	['model'] = 'it18',
	['price'] = 17000,
	['category'] = 'italdesign',
	['categoryLabel'] = 'italdesign',
	['hash'] = `it18`,
	['shop'] = 'import',
},
['fpacehm'] = {
	['name'] = 'Jaguar F-pace 2017 Hamann Edition',
	['brand'] = 'jaguar',
	['model'] = 'fpacehm',
	['price'] = 50000,
	['category'] = 'jaguar',
	['categoryLabel'] = 'jaguar',
	['hash'] = `fpacehm`,
	['shop'] = 'import',
},
['jeep2012'] = {
	['name'] = '2012 Jeep Wrangler',
	['brand'] = 'jeep',
	['model'] = 'jeep2012',
	['price'] = 47500,
	['category'] = 'jeep',
	['categoryLabel'] = 'jeep',
	['hash'] = `jeep2012`,
	['shop'] = 'import',
},
['jeepreneg'] = {
	['name'] = 'Jeep Renegade',
	['brand'] = 'jeep',
	['model'] = 'jeepreneg',
	['price'] = 40000,
	['category'] = 'jeep',
	['categoryLabel'] = 'jeep',
	['hash'] = `jeepreneg`,
	['shop'] = 'import',
},
['srt8'] = {
	['name'] = '2015 Jeep SRT-8',
	['brand'] = 'jeep',
	['model'] = 'srt8',
	['price'] = 35000,
	['category'] = 'jeep',
	['categoryLabel'] = 'jeep',
	['hash'] = `srt8`,
	['shop'] = 'import',
},
['trhawk'] = {
	['name'] = '2018 Jeep Grand Cherokee',
	['brand'] = 'jeep',
	['model'] = 'trhawk',
	['price'] = 16000,
	['category'] = 'jeep',
	['categoryLabel'] = 'jeep',
	['hash'] = `trhawk`,
	['shop'] = 'import',
},
['agerars'] = {
	['name'] = '2017 Koenigsegg Agera RS',
	['brand'] = 'koenigsegg',
	['model'] = 'agerars',
	['price'] = 40000,
	['category'] = 'koenigsegg',
	['categoryLabel'] = 'koenigsegg',
	['hash'] = `agerars`,
	['shop'] = 'import',
},
['regera'] = {
	['name'] = 'Koenigsegg Regera',
	['brand'] = 'koenigsegg',
	['model'] = 'regera',
	['price'] = 55000,
	['category'] = 'koenigsegg',
	['categoryLabel'] = 'koenigsegg',
	['hash'] = `regera`,
	['shop'] = 'import',
},
['huracanst'] = {
	['name'] = 'Lamborghini Huracan Super Trofeo',
	['brand'] = 'lamborghini',
	['model'] = 'huracanst',
	['price'] = 29000,
	['category'] = 'lamborghini',
	['categoryLabel'] = 'lamborghini',
	['hash'] = `huracanst`,
	['shop'] = 'import',
},
['lambose'] = {
	['name'] = 'Lamborghini Sesto Elemento',
	['brand'] = 'lamborghini',
	['model'] = 'lambose',
	['price'] = 45000,
	['category'] = 'lamborghini',
	['categoryLabel'] = 'lamborghini',
	['hash'] = `lambose`,
	['shop'] = 'import',
},
['lp670sv'] = {
	['name'] = '2009 Lamborghini Murcielago LP 670-4 SV',
	['brand'] = 'lamborghini',
	['model'] = 'lp670sv',
	['price'] = 25000,
	['category'] = 'lamborghini',
	['categoryLabel'] = 'lamborghini',
	['hash'] = `lp670sv`,
	['shop'] = 'import',
},
['lp700r'] = {
	['name'] = '2013 Lamborghini Aventador LP700-4 Roadster',
	['brand'] = 'lamborghini',
	['model'] = 'lp700r',
	['price'] = 32000,
	['category'] = 'lamborghini',
	['categoryLabel'] = 'lamborghini',
	['hash'] = `lp700r`,
	['shop'] = 'import',
},
['svj63'] = {
	['name'] = 'Lamborghini Aventador SVJ',
	['brand'] = 'lamborghini',
	['model'] = 'svj63',
	['price'] = 62000,
	['category'] = 'lamborghini',
	['categoryLabel'] = 'lamborghini',
	['hash'] = `svj63`,
	['shop'] = 'import',
},
['urus'] = {
	['name'] = 'Lamborghini Urus',
	['brand'] = 'lamborghini',
	['model'] = 'urus',
	['price'] = 85000,
	['category'] = 'lamborghini',
	['categoryLabel'] = 'lamborghini',
	['hash'] = `urus`,
	['shop'] = 'import',
},
['veneno'] = {
	['name'] = 'Lamborghini Veneno',
	['brand'] = 'lamborghini',
	['model'] = 'veneno',
	['price'] = 155000,
	['category'] = 'lamborghini',
	['categoryLabel'] = 'lamborghini',
	['hash'] = `veneno`,
	['shop'] = 'import',
},
['gs350'] = {
	['name'] = 'Lexus GS 350',
	['brand'] = 'lexus',
	['model'] = 'gs350',
	['price'] = 30000,
	['category'] = 'lexus',
	['categoryLabel'] = 'lexus',
	['hash'] = `gs350`,
	['shop'] = 'import',
},
['is350mod'] = {
	['name'] = '2014 Lexus IS 350',
	['brand'] = 'lexus',
	['model'] = 'is350mod',
	['price'] = 40000,
	['category'] = 'lexus',
	['categoryLabel'] = 'lexus',
	['hash'] = `is350mod`,
	['shop'] = 'import',
},
['rcf'] = {
	['name'] = '2015 Lexus RCF',
	['brand'] = 'lexus',
	['model'] = 'rcf',
	['price'] = 12800,
	['category'] = 'lexus',
	['categoryLabel'] = 'lexus',
	['hash'] = `rcf`,
	['shop'] = 'import',
},
['lrrr'] = {
	['name'] = '1973 Land Rover Range Rover',
	['brand'] = 'landrover',
	['model'] = 'lrrr',
	['price'] = 55000,
	['category'] = 'landrover',
	['categoryLabel'] = 'landrover',
	['hash'] = `lrrr`,
	['shop'] = 'import',
},
['esprit02'] = {
	['name'] = '2002 Lotus Esprit V8',
	['brand'] = 'lotus',
	['model'] = 'esprit02',
	['price'] = 20000,
	['category'] = 'lotus',
	['categoryLabel'] = 'lotus',
	['hash'] = `esprit02`,
	['shop'] = 'import',
},
['regalia'] = {
	['name'] = 'Quartz Regalia 723',
	['brand'] = 'quartz',
	['model'] = 'regalia',
	['price'] = 80000,
	['category'] = 'quartz',
	['categoryLabel'] = 'quartz',
	['hash'] = `regalia`,
	['shop'] = 'import',
},
['levante'] = {
	['name'] = 'Maserati Levante',
	['brand'] = 'maserati',
	['model'] = 'levante',
	['price'] = 75000,
	['category'] = 'maserati',
	['categoryLabel'] = 'maserati',
	['hash'] = `levante`,
	['shop'] = 'import',
},
['84rx7k'] = {
	['name'] = '1984 Mazda RX-7 Stanced Version',
	['brand'] = 'mazda',
	['model'] = '84rx7k',
	['price'] = 65000,
	['category'] = 'mazda',
	['categoryLabel'] = 'mazda',
	['hash'] = `84rx7k`,
	['shop'] = 'import',
},
['dragfd'] = {
	['name'] = '2002 Mazda RX-7 FD Drag',
	['brand'] = 'mazda',
	['model'] = 'dragfd',
	['price'] = 220000,
	['category'] = 'mazda',
	['categoryLabel'] = 'mazda',
	['hash'] = `dragfd`,
	['shop'] = 'import',
},
['fc3s'] = {
	['name'] = 'Mazda RX7 FC3S',
	['brand'] = 'mazda',
	['model'] = 'fc3s',
	['price'] = 12000,
	['category'] = 'mazda',
	['categoryLabel'] = 'mazda',
	['hash'] = `fc3s`,
	['shop'] = 'import',
},
['majfd'] = {
	['name'] = 'Mazda RX-7 FD',
	['brand'] = 'mazda',
	['model'] = 'majfd',
	['price'] = 16000,
	['category'] = 'mazda',
	['categoryLabel'] = 'mazda',
	['hash'] = `majfd`,
	['shop'] = 'import',
},
['miata3'] = {
	['name'] = '1989 Mazda Miata NA',
	['brand'] = 'mazda',
	['model'] = 'miata3',
	['price'] = 6500,
	['category'] = 'mazda',
	['categoryLabel'] = 'mazda',
	['hash'] = `miata3`,
	['shop'] = 'import',
},
['na6'] = {
	['name'] = 'Mazda MX-5 Miata (NA6C)',
	['brand'] = 'mazda',
	['model'] = 'na6',
	['price'] = 8500,
	['category'] = 'mazda',
	['categoryLabel'] = 'mazda',
	['hash'] = `na6`,
	['shop'] = 'import',
},
['650s'] = {
	['name'] = 'McLaren 650S Coupe',
	['brand'] = 'mclaren',
	['model'] = '650s',
	['price'] = 45000,
	['category'] = 'mclaren',
	['categoryLabel'] = 'mclaren',
	['hash'] = `650s`,
	['shop'] = 'import',
},
['675lt'] = {
	['name'] = '2016 McLaren 675LT Coupe',
	['brand'] = 'mclaren',
	['model'] = '675lt',
	['price'] = 120000,
	['category'] = 'mclaren',
	['categoryLabel'] = 'mclaren',
	['hash'] = `675lt`,
	['shop'] = 'import',
},
['720s'] = {
	['name'] = '2017 McLaren 720S',
	['brand'] = 'mclaren',
	['model'] = '720s',
	['price'] = 8000,
	['category'] = 'mclaren',
	['categoryLabel'] = 'mclaren',
	['hash'] = `720s`,
	['shop'] = 'import',
},
['gtr96'] = {
	['name'] = '1996 McLaren F1 GTR',
	['brand'] = 'mclaren',
	['model'] = 'gtr96',
	['price'] = 45000,
	['category'] = 'mclaren',
	['categoryLabel'] = 'mclaren',
	['hash'] = `gtr96`,
	['shop'] = 'import',
},
['mcst'] = {
	['name'] = '2020 McLaren Speedtail',
	['brand'] = 'mclaren',
	['model'] = 'mcst',
	['price'] = 35000,
	['category'] = 'mclaren',
	['categoryLabel'] = 'mclaren',
	['hash'] = `mcst`,
	['shop'] = 'import',
},
['mp412c'] = {
	['name'] = 'McLaren MP4-12C',
	['brand'] = 'mclaren',
	['model'] = 'mp412c',
	['price'] = 55000,
	['category'] = 'mclaren',
	['categoryLabel'] = 'mclaren',
	['hash'] = `mp412c`,
	['shop'] = 'import',
},
['senna'] = {
	['name'] = '2019 McLaren Senna',
	['brand'] = 'mclaren',
	['model'] = 'senna',
	['price'] = 210000,
	['category'] = 'mclaren',
	['categoryLabel'] = 'mclaren',
	['hash'] = `senna`,
	['shop'] = 'import',
},
['amggtrr20'] = {
	['name'] = '2020 Mercedes-Benz AMG GT-R Roadster',
	['brand'] = 'mercedesbenz',
	['model'] = 'amggtrr20',
	['price'] = 60000,
	['category'] = 'mercedesbenz',
	['categoryLabel'] = 'mercedesbenz',
	['hash'] = `amggtrr20`,
	['shop'] = 'import',
},
['c6320'] = {
	['name'] = '2020 Mercedes-AMG C63s',
	['brand'] = 'mercedesamg',
	['model'] = 'c6320',
	['price'] = 80000,
	['category'] = 'mercedesbenz',
	['categoryLabel'] = 'mercedesbenz',
	['hash'] = `c6320`,
	['shop'] = 'import',
},
['G65'] = {
	['name'] = '2013 Mercedes-Benz G65 AMG',
	['brand'] = 'mercedesbenz',
	['model'] = 'G65',
	['price'] = 55000,
	['category'] = 'mercedesbenz',
	['categoryLabel'] = 'mercedesbenz',
	['hash'] = `G65`,
	['shop'] = 'import',
},
['e400'] = {
	['name'] = '2019 Mercedes-Benz E400 Coupe 4matic (C238)',
	['brand'] = 'mercedesbenz',
	['model'] = 'e400',
	['price'] = 32000,
	['category'] = 'mercedesbenz',
	['categoryLabel'] = 'mercedesbenz',
	['hash'] = `e400`,
	['shop'] = 'import',
},
['gl63'] = {
	['name'] = 'Mercedes-Benz GL63 AMG',
	['brand'] = 'mercedesbenz',
	['model'] = 'gl63',
	['price'] = 40000,
	['category'] = 'mercedesbenz',
	['categoryLabel'] = 'mercedesbenz',
	['hash'] = `gl63`,
	['shop'] = 'import',
},
['mbc63'] = {
	['name'] = '2012 Mercedes-Benz C63 AMG Coupe Black Series',
	['brand'] = 'mercedesbenz',
	['model'] = 'mbc63',
	['price'] = 42000,
	['category'] = 'mercedesbenz',
	['categoryLabel'] = 'mercedesbenz',
	['hash'] = `mbc63`,
	['shop'] = 'import',
},
['s500w222'] = {
	['name'] = '2014 Mercedes-Benz S500 W222',
	['brand'] = 'mercedesbenz',
	['model'] = 's500w222',
	['price'] = 55000,
	['category'] = 'mercedesbenz',
	['categoryLabel'] = 'mercedesbenz',
	['hash'] = `s500w222`,
	['shop'] = 'import',
},
['sl500'] = {
	['name'] = '1995 Mercedes-Benz SL500',
	['brand'] = 'mercedesbenz',
	['model'] = 'sl500',
	['price'] = 38000,
	['category'] = 'mercedesbenz',
	['categoryLabel'] = 'mercedesbenz',
	['hash'] = `sl500`,
	['shop'] = 'import',
},
['v250'] = {
	['name'] = 'Mercedes-Benz V-class 250 Bluetec LWB',
	['brand'] = 'mercedesbenz',
	['model'] = 'v250',
	['price'] = 35000,
	['category'] = 'mercedesbenz',
	['categoryLabel'] = 'mercedesbenz',
	['hash'] = `v250`,
	['shop'] = 'import',
},
['cp9a'] = {
	['name'] = 'Mitsubishi Lancer Evo VI T.M.E (CP9A)',
	['brand'] = 'mitsubishi',
	['model'] = 'cp9a',
	['price'] = 32000,
	['category'] = 'mitsubishi',
	['categoryLabel'] = 'mitsubishi',
	['hash'] = `cp9a`,
	['shop'] = 'import',
},
['fto'] = {
	['name'] = 'Mitsubishi FTO GP Version-R',
	['brand'] = 'mitsubishi',
	['model'] = 'fto',
	['price'] = 40000,
	['category'] = 'mitsubishi',
	['categoryLabel'] = 'mitsubishi',
	['hash'] = `fto`,
	['shop'] = 'import',
},
['180sx'] = {
	['name'] = 'Nissan 180SX Type-X',
	['brand'] = 'nissan',
	['model'] = '180sx',
	['price'] = 95000,
	['category'] = 'nissan',
	['categoryLabel'] = 'nissan',
	['hash'] = `180sx`,
	['shop'] = 'import',
},
['gtr'] = {
	['name'] = '2017 Nissan GTR',
	['brand'] = 'nissan',
	['model'] = 'gtr',
	['price'] = 125000,
	['category'] = 'nissan',
	['categoryLabel'] = 'nissan',
	['hash'] = `gtr`,
	['shop'] = 'import',
},
['gtrc'] = {
	['name'] = '2017 R35 Nissan GTR Convertible',
	['brand'] = 'nissan',
	['model'] = 'gtrc',
	['price'] = 36000,
	['category'] = 'nissan',
	['categoryLabel'] = 'nissan',
	['hash'] = `gtrc`,
	['shop'] = 'import',
},
['maj350'] = {
	['name'] = 'Nissan Fairlady Z Z33',
	['brand'] = 'nissan',
	['model'] = 'maj350',
	['price'] = 45000,
	['category'] = 'nissan',
	['categoryLabel'] = 'nissan',
	['hash'] = `maj350`,
	['shop'] = 'import',
},
['nis15'] = {
	['name'] = 'Nissan Silvia S15 Spec-R',
	['brand'] = 'nissan',
	['model'] = 'nis15',
	['price'] = 65000,
	['category'] = 'nissan',
	['categoryLabel'] = 'nissan',
	['hash'] = `nis15`,
	['shop'] = 'import',
},
['nissantitan17'] = {
	['name'] = '2017 Nissan Titan Warrior',
	['brand'] = 'nissan',
	['model'] = 'nissantitan17',
	['price'] = 80000,
	['category'] = 'nissan',
	['categoryLabel'] = 'nissan',
	['hash'] = `nissantitan17`,
	['shop'] = 'import',
},
['ns350'] = {
	['name'] = 'Nissan 350z Stardast',
	['brand'] = 'nissan',
	['model'] = 'ns350',
	['price'] = 60000,
	['category'] = 'nissan',
	['categoryLabel'] = 'nissan',
	['hash'] = `ns350`,
	['shop'] = 'import',
},
['nzp'] = {
	['name'] = 'Nissan 370z Pandem',
	['brand'] = 'nissan',
	['model'] = 'nzp',
	['price'] = 70000,
	['category'] = 'nissan',
	['categoryLabel'] = 'nissan',
	['hash'] = `nzp`,
	['shop'] = 'import',
},
['s14'] = {
	['name'] = '1998 Nissan Silvia K',
	['brand'] = 'nissan',
	['model'] = 's14',
	['price'] = 55000,
	['category'] = 'nissan',
	['categoryLabel'] = 'nissan',
	['hash'] = `s14`,
	['shop'] = 'import',
},
['Safari97'] = {
	['name'] = '1997 Nissan Patrol Super Safari Y60',
	['brand'] = 'nissan',
	['model'] = 'Safari97',
	['price'] = 12000,
	['category'] = 'nissan',
	['categoryLabel'] = 'nissan',
	['hash'] = `Safari97`,
	['shop'] = 'import',
},
['skyline'] = {
	['name'] = 'Nissan Skyline GT-R (BNR34)',
	['brand'] = 'nissan',
	['model'] = 'skyline',
	['price'] = 20000,
	['category'] = 'nissan',
	['categoryLabel'] = 'nissan',
	['hash'] = `skyline`,
	['shop'] = 'import',
},
['z32'] = {
	['name'] = 'Nissan 300ZX Z32',
	['brand'] = 'nissan',
	['model'] = 'z32',
	['price'] = 75000,
	['category'] = 'nissan',
	['categoryLabel'] = 'nissan',
	['hash'] = `z32`,
	['shop'] = 'import',
},
['maj935'] = {
	['name'] = '1978 Porsche 935 Moby Dick',
	['brand'] = 'porsche',
	['model'] = 'maj935',
	['price'] = 65000,
	['category'] = 'porsche',
	['categoryLabel'] = 'porsche',
	['hash'] = `maj935`,
	['shop'] = 'import',
},
['pcs18'] = {
	['name'] = '2018 Porsche Cayenne S',
	['brand'] = 'porsche',
	['model'] = 'pcs18',
	['price'] = 65000,
	['category'] = 'porsche',
	['categoryLabel'] = 'porsche',
	['hash'] = `pcs18`,
	['shop'] = 'import',
},
['718caymans'] = {
	['name'] = 'Porsche 718 Cayman S',
	['brand'] = 'porsche',
	['model'] = '718caymans',
	['price'] = 80000,
	['category'] = 'porsche',
	['categoryLabel'] = 'porsche',
	['hash'] = `718caymans`,
	['shop'] = 'import',
},
['cgt'] = {
	['name'] = '2003 Porsche Carrera GT (980)',
	['brand'] = 'porsche',
	['model'] = 'cgt',
	['price'] = 38500,
	['category'] = 'porsche',
	['categoryLabel'] = 'porsche',
	['hash'] = `cgt`,
	['shop'] = 'import',
},
['pm19'] = {
	['name'] = '2019 Porsche Macan Turbo',
	['brand'] = 'porsche',
	['model'] = 'pm19',
	['price'] = 55000,
	['category'] = 'porsche',
	['categoryLabel'] = 'porsche',
	['hash'] = `pm19`,
	['shop'] = 'import',
},
['taycan'] = {
	['name'] = '2020 Porsche Taycan Turbo S',
	['brand'] = 'porsche',
	['model'] = 'taycan',
	['price'] = 45000,
	['category'] = 'porsche',
	['categoryLabel'] = 'porsche',
	['hash'] = `taycan`,
	['shop'] = 'import',
},
['yPG205t16B'] = {
	['name'] = 'Peugeot 205 Turbo 16',
	['brand'] = 'peugeot',
	['model'] = 'yPG205t16B',
	['price'] = 45000,
	['category'] = 'peugeot',
	['categoryLabel'] = 'peugeot',
	['hash'] = `yPG205t16B`,
	['shop'] = 'import',
},
['yPG205t16A'] = {
	['name'] = 'Peugeot 205 Rally',
	['brand'] = 'peugeot',
	['model'] = 'yPG205t16A',
	['price'] = 45000,
	['category'] = 'peugeot',
	['categoryLabel'] = 'peugeot',
	['hash'] = `yPG205t16A`,
	['shop'] = 'import',
},
['twingo'] = {
	['name'] = 'Renault Twingo I',
	['brand'] = 'renault',
	['model'] = 'twingo',
	['price'] = 45000,
	['category'] = 'renault',
	['categoryLabel'] = 'renault',
	['hash'] = `twingo`,
	['shop'] = 'import',
},
['rrevoque'] = {
	['name'] = 'Range Rover Evoque',
	['brand'] = 'rangerover',
	['model'] = 'rrevoque',
	['price'] = 40000,
	['category'] = 'rangerover',
	['categoryLabel'] = 'rangerover',
	['hash'] = `rrevoque`,
	['shop'] = 'import',
},
['rrst'] = {
	['name'] = 'Range Rover Vogue Startech',
	['brand'] = 'rangerover',
	['model'] = 'rrst',
	['price'] = 65000,
	['category'] = 'rangerover',
	['categoryLabel'] = 'rangerover',
	['hash'] = `rrst`,
	['shop'] = 'import',
},
['rsvr16'] = {
	['name'] = '2016 Range Rover Sport SVR',
	['brand'] = 'rangerover',
	['model'] = 'rsvr16',
	['price'] = 135000,
	['category'] = 'rangerover',
	['categoryLabel'] = 'rangerover',
	['hash'] = `rsvr16`,
	['shop'] = 'import',
},
['dawnonyx'] = {
	['name'] = '2016 Rolls-Royce Dawn Onyx',
	['brand'] = 'rollsroyce',
	['model'] = 'dawnonyx',
	['price'] = 38000,
	['category'] = 'rollsroyce',
	['categoryLabel'] = 'rollsroyce',
	['hash'] = `dawnonyx`,
	['shop'] = 'import',
},
['wraith'] = {
	['name'] = 'Rolls-Royce Wraith',
	['brand'] = 'rollsroyce',
	['model'] = 'wraith',
	['price'] = 30000,
	['category'] = 'rollsroyce',
	['categoryLabel'] = 'rollsroyce',
	['hash'] = `wraith`,
	['shop'] = 'import',
},
['rculi'] = {
	['name'] = 'Rolls Royce Cullinan',
	['brand'] = 'rollsroyce',
	['model'] = 'rculi',
	['price'] = 40000,
	['category'] = 'rollsroyce',
	['categoryLabel'] = 'rollsroyce',
	['hash'] = `rculi`,
	['shop'] = 'import',
},
['rrphantom'] = {
	['name'] = '2018 Rolls-Royce Phantom VIII',
	['brand'] = 'rollsroyce',
	['model'] = 'rrphantom',
	['price'] = 70000,
	['category'] = 'rollsroyce',
	['categoryLabel'] = 'rollsroyce',
	['hash'] = `rrphantom`,
	['shop'] = 'import',
},
['subisti08'] = {
	['name'] = '2008 Subaru WRX STi',
	['brand'] = 'subaru',
	['model'] = 'subisti08',
	['price'] = 65000,
	['category'] = 'subaru',
	['categoryLabel'] = 'subaru',
	['hash'] = `subisti08`,
	['shop'] = 'import',
},
['subwrx'] = {
	['name'] = '2004 Subaru Impreza WRX STI',
	['brand'] = 'subaru',
	['model'] = 'subwrx',
	['price'] = 130000,
	['category'] = 'subaru',
	['categoryLabel'] = 'subaru',
	['hash'] = `subwrx`,
	['shop'] = 'import',
},
['svx'] = {
	['name'] = '1996 Subaru Alcyone SVX',
	['brand'] = 'subaru',
	['model'] = 'svx',
	['price'] = 35000,
	['category'] = 'subaru',
	['categoryLabel'] = 'subaru',
	['hash'] = `svx`,
	['shop'] = 'import',
},
['gsxr19'] = {
	['name'] = '2019 Suzuki GSX-R1000R',
	['brand'] = 'suzuki',
	['model'] = 'gsxr19',
	['price'] = 28000,
	['category'] = 'suzuki',
	['categoryLabel'] = 'suzuki',
	['hash'] = `gsxr19`,
	['shop'] = 'import',
},
['katana'] = {
	['name'] = '2019 Suzuki Katana',
	['brand'] = 'suzuki',
	['model'] = 'katana',
	['price'] = 35000,
	['category'] = 'suzuki',
	['categoryLabel'] = 'suzuki',
	['hash'] = `katana`,
	['shop'] = 'import',
},
['tr22'] = {
	['name'] = '2020 Tesla Roadster',
	['brand'] = 'tesla',
	['model'] = 'tr22',
	['price'] = 45000,
	['category'] = 'tesla',
	['categoryLabel'] = 'tesla',
	['hash'] = `tr22`,
	['shop'] = 'import',
},
['p90d'] = {
	['name'] = 'Tesla Model X Performance',
	['brand'] = 'tesla',
	['model'] = 'p90d',
	['price'] = 50000,
	['category'] = 'tesla',
	['categoryLabel'] = 'tesla',
	['hash'] = `p90d`,
	['shop'] = 'import',
},
['models'] = {
	['name'] = '2016 Tesla Model S P90D',
	['brand'] = 'tesla',
	['model'] = 'models',
	['price'] = 39500,
	['category'] = 'tesla',
	['categoryLabel'] = 'tesla',
	['hash'] = `models`,
	['shop'] = 'import',
},
['tmodel'] = {
	['name'] = '2018 Tesla Model 3',
	['brand'] = 'tesla',
	['model'] = 'tmodel',
	['price'] = 15000,
	['category'] = 'tesla',
	['categoryLabel'] = 'tesla',
	['hash'] = `tmodel`,
	['shop'] = 'import',
},
['teslax'] = {
	['name'] = '2016 Tesla Model X P90D',
	['brand'] = 'tesla',
	['model'] = 'teslax',
	['price'] = 50000,
	['category'] = 'tesla',
	['categoryLabel'] = 'tesla',
	['hash'] = `teslax`,
	['shop'] = 'import',
},
['teslapd'] = {
	['name'] = '2017 Tesla Model S',
	['brand'] = 'tesla',
	['model'] = 'teslapd',
	['price'] = 40000,
	['category'] = 'tesla',
	['categoryLabel'] = 'tesla',
	['hash'] = `teslapd`,
	['shop'] = 'import',
},
['cam8tun'] = {
	['name'] = '2018 Toyota Camry XSE',
	['brand'] = 'toyota',
	['model'] = 'cam8tun',
	['price'] = 70000,
	['category'] = 'toyota',
	['categoryLabel'] = 'toyota',
	['hash'] = `cam8tun`,
	['shop'] = 'import',
},
['vxr'] = {
	['name'] = '2016 Toyota Land Cruiser VXR',
	['brand'] = 'toyota',
	['model'] = 'vxr',
	['price'] = 900000,
	['category'] = 'toyota',
	['categoryLabel'] = 'toyota',
	['hash'] = `vxr`,
	['shop'] = 'import',
},
['toysupmk4'] = {
	['name'] = '1998 Toyota Supra Turbo (A80)',
	['brand'] = 'toyota',
	['model'] = 'toysupmk4',
	['price'] = 255000,
	['category'] = 'toyota',
	['categoryLabel'] = 'toyota',
	['hash'] = `toysupmk4`,
	['shop'] = 'import',
},
['mk2100'] = {
	['name'] = 'Toyota Mark II JZX100',
	['brand'] = 'toyota',
	['model'] = 'mk2100',
	['price'] = 90000,
	['category'] = 'toyota',
	['categoryLabel'] = 'toyota',
	['hash'] = `mk2100`,
	['shop'] = 'import',
},
['golfgti7'] = {
	['name'] = '2015 Volkswagen Golf GTI MK7',
	['brand'] = 'volkswagen',
	['model'] = 'golfgti7',
	['price'] = 375000,
	['category'] = 'volkswagen',
	['categoryLabel'] = 'volkswagen',
	['hash'] = `golfgti7`,
	['shop'] = 'import',
},
['passat'] = {
	['name'] = '2016 Volkswagen Passat B8',
	['brand'] = 'volkswagen',
	['model'] = 'passat',
	['price'] = 375000,
	['category'] = 'volkswagen',
	['categoryLabel'] = 'volkswagen',
	['hash'] = `passat`,
	['shop'] = 'import',
},
['vwr'] = {
	['name'] = 'Volkswagen Scirocco R 2011',
	['brand'] = 'volkswagen',
	['model'] = 'vwr',
	['price'] = 375000,
	['category'] = 'volkswagen',
	['categoryLabel'] = 'volkswagen',
	['hash'] = `vwr`,
	['shop'] = 'import',
},
['amarok'] = {
	['name'] = '2018 Volkswagen Amarok V6',
	['brand'] = 'volkswagen',
	['model'] = 'amarok',
	['price'] = 375000,
	['category'] = 'volkswagen',
	['categoryLabel'] = 'volkswagen',
	['hash'] = `amarok`,
	['shop'] = 'import',
},
['xc90'] = {
	['name'] = 'Volvo XC90 T8',
	['brand'] = 'volvo',
	['model'] = 'xc90',
	['price'] = 425000,
	['category'] = 'volvo',
	['categoryLabel'] = 'volvo',
	['hash'] = `xc90`,
	['shop'] = 'import',
},
['wmfenyr'] = {
	['name'] = 'W-Motors Fenyr Supersport',
	['brand'] = 'wmotors',
	['model'] = 'wmfenyr',
	['price'] = 220000,
	['category'] = 'wmotors',
	['categoryLabel'] = 'wmotors',
	['hash'] = `wmfenyr`,
	['shop'] = 'import',
},
['lykan'] = {
	['name'] = 'W-Motors Lykan HyperSport',
	['brand'] = 'wmotors',
	['model'] = 'lykan',
	['price'] = 185000,
	['category'] = 'wmotors',
	['categoryLabel'] = 'wmotors',
	['hash'] = `lykan`,
	['shop'] = 'import',
},
